### ISSUE TITLE
OrderBy doesn't work if DataGridStateProvider is used

### ISSUE THREAD

**Issue by mvitzthum** [DCCS-IT-Business-Solutions/react-datagrid-mui#3]
![image](https://user-images.githubusercontent.com/47003029/58176728-3576c380-7ca3-11e9-9597-d3554efddf05.png)

Change:
if (state.orderBy && state.orderBy.prop === colDef.prop) {
      desc = !state.desc;
    }

**Comment by stephanmeissner** [comment]
fixed in version 1.0.5
